export const LINK_SUCCESS="LINK_SUCCESS";
export const LINK_FAIL="LINK_FAIL";

export const CALENDAR_LOAD_SUCCESS="CALENDAR_LOAD_SUCCESS";
export const CALENDAR_LOAD_FAIL="CALENDAR_LOAD_FAIL";

export const SCOREBOARD_LOAD_SUCCESS="SCOREBOARD_LOAD_SUCCESS";
export const SCOREBOARD_LOAD_FAIL="SCOREBOARD_LOAD_FAIL";

export const TEAMS_LOAD_SUCCESS="TEAMS_LOAD_SUCCESS";
export const TEAMS_LOAD_FAIL="TEAMS_LOAD_FAIL";

export const TEAM_LOAD_SUCCESS="TEAM_LOAD_SUCCESS";
export const TEAM_LOAD_FAIL="TEAM_LOAD_FAIL";
