export const LINK_SUCCESS="LINK_SUCCESS";
export const LINK_FAIL="LINK_FAIL";

export const CALENDER_LOAD_SUCCESS="CALENDER_LOAD_SUCCESS";
export const CALENDER_LOAD_FAIL="CALENDER_LOAD_FAIL";

export const SCOREBOARD_LOAD_SUCCESS="SCOREBOARD_LOAD_SUCCESS";
export const SCOREBOARD_LOAD_FAIL="SCOREBOARD_LOAD_FAIL";

export const TEAMS_LOAD_SUCCESS="TEAMS_LOAD_SUCCESS";
export const TEAMS_LOAD_FAIL="TEAMS_LOAD_FAIL";